### ISSUE TITLE
Issues after browser refresh

### ISSUE THREAD

**Issue by cesarcarc** [open-simulation-platform/cosim-demo-app#143]
Two scenarios were identified. This has been tested on Chrome (Version 81.0.4044.122 (Official Build) (64-bit)). Tests were performed with version 0.5.1 and 0.6.0 (after the release of cse-core). 

----
**Scenario 1:**

Setup
- Run cse-server-go, load house demo, press play

Action 1:
- While running, have the "simulation status" page open. Press refresh
 
Result 1:
- Models disappear (Not ok)

Action 2:
- Click on a trend and refresh browser

Result 2:
- Models are now displayed (ok)

----
**Scenario 2:**

Setup
- Run cse-server-go (start it again), load house demo, press play

Action:
- While running, have one of the trends page open. Press refresh

Result:
- Models don't disappear (ok)
- Trend freezes (not ok)
- A lot of data is dumped to the terminal (not ok)

------

Depending on the page you are when you hit refresh, the models will disappear or not (but that is only applicable for the first refresh).

**Comment by eidekrist** [comment]
Split off scenario #2 as a separate issue, see #177.
